name: Generate Snake Animation

on:
  schedule: # Executa todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: jaocoqueiro
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir resultado para a branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
